// Code generated by gen/main.go; DO NOT EDIT.

package gsr

import (
	"time"
)

// AnyValue holds a value and provides direct type conversion methods that return T.
// On conversion failure, methods return the zero value of T.
type AnyValue interface {
	// To returns an AnyTo navigator for choosing between Value, ValueE, Pointer, and PointerE modes.
	To() AnyTo
	// Pointer returns an AnyPointer for pointer-returning conversions.
	Pointer() AnyPointer
	// Bool converts the value to bool, returning the zero value on error.
	Bool() bool
	// String converts the value to string, returning the zero value on error.
	String() string
	// Int converts the value to int, returning the zero value on error.
	Int() int
	// Int8 converts the value to int8, returning the zero value on error.
	Int8() int8
	// Int16 converts the value to int16, returning the zero value on error.
	Int16() int16
	// Int32 converts the value to int32, returning the zero value on error.
	Int32() int32
	// Int64 converts the value to int64, returning the zero value on error.
	Int64() int64
	// Uint converts the value to uint, returning the zero value on error.
	Uint() uint
	// Uint8 converts the value to uint8, returning the zero value on error.
	Uint8() uint8
	// Uint16 converts the value to uint16, returning the zero value on error.
	Uint16() uint16
	// Uint32 converts the value to uint32, returning the zero value on error.
	Uint32() uint32
	// Uint64 converts the value to uint64, returning the zero value on error.
	Uint64() uint64
	// Float32 converts the value to float32, returning the zero value on error.
	Float32() float32
	// Float64 converts the value to float64, returning the zero value on error.
	Float64() float64
	// Time converts the value to time.Time, returning the zero value on error.
	Time() time.Time
	// Duration converts the value to time.Duration, returning the zero value on error.
	Duration() time.Duration
	// Slice converts the value to []any, returning the zero value on error.
	Slice() []any
	// BoolSlice converts the value to []bool, returning the zero value on error.
	BoolSlice() []bool
	// StringSlice converts the value to []string, returning the zero value on error.
	StringSlice() []string
	// IntSlice converts the value to []int, returning the zero value on error.
	IntSlice() []int
	// Int8Slice converts the value to []int8, returning the zero value on error.
	Int8Slice() []int8
	// Int16Slice converts the value to []int16, returning the zero value on error.
	Int16Slice() []int16
	// Int32Slice converts the value to []int32, returning the zero value on error.
	Int32Slice() []int32
	// Int64Slice converts the value to []int64, returning the zero value on error.
	Int64Slice() []int64
	// UintSlice converts the value to []uint, returning the zero value on error.
	UintSlice() []uint
	// Uint8Slice converts the value to []uint8, returning the zero value on error.
	Uint8Slice() []uint8
	// Uint16Slice converts the value to []uint16, returning the zero value on error.
	Uint16Slice() []uint16
	// Uint32Slice converts the value to []uint32, returning the zero value on error.
	Uint32Slice() []uint32
	// Uint64Slice converts the value to []uint64, returning the zero value on error.
	Uint64Slice() []uint64
	// Float32Slice converts the value to []float32, returning the zero value on error.
	Float32Slice() []float32
	// Float64Slice converts the value to []float64, returning the zero value on error.
	Float64Slice() []float64
	// DurationSlice converts the value to []time.Duration, returning the zero value on error.
	DurationSlice() []time.Duration
	// StringMap converts the value to map[string]any, returning the zero value on error.
	StringMap() map[string]any
	// StringMapString converts the value to map[string]string, returning the zero value on error.
	StringMapString() map[string]string
	// StringMapStringSlice converts the value to map[string][]string, returning the zero value on error.
	StringMapStringSlice() map[string][]string
	// StringMapBool converts the value to map[string]bool, returning the zero value on error.
	StringMapBool() map[string]bool
	// StringMapInt converts the value to map[string]int, returning the zero value on error.
	StringMapInt() map[string]int
	// StringMapInt64 converts the value to map[string]int64, returning the zero value on error.
	StringMapInt64() map[string]int64
}

// AnyValueE holds a value and provides type conversion methods that return (T, error).
type AnyValueE interface {
	// Bool converts the value to bool, returning an error on failure.
	Bool() (bool, error)
	// String converts the value to string, returning an error on failure.
	String() (string, error)
	// Int converts the value to int, returning an error on failure.
	Int() (int, error)
	// Int8 converts the value to int8, returning an error on failure.
	Int8() (int8, error)
	// Int16 converts the value to int16, returning an error on failure.
	Int16() (int16, error)
	// Int32 converts the value to int32, returning an error on failure.
	Int32() (int32, error)
	// Int64 converts the value to int64, returning an error on failure.
	Int64() (int64, error)
	// Uint converts the value to uint, returning an error on failure.
	Uint() (uint, error)
	// Uint8 converts the value to uint8, returning an error on failure.
	Uint8() (uint8, error)
	// Uint16 converts the value to uint16, returning an error on failure.
	Uint16() (uint16, error)
	// Uint32 converts the value to uint32, returning an error on failure.
	Uint32() (uint32, error)
	// Uint64 converts the value to uint64, returning an error on failure.
	Uint64() (uint64, error)
	// Float32 converts the value to float32, returning an error on failure.
	Float32() (float32, error)
	// Float64 converts the value to float64, returning an error on failure.
	Float64() (float64, error)
	// Time converts the value to time.Time, returning an error on failure.
	Time() (time.Time, error)
	// Duration converts the value to time.Duration, returning an error on failure.
	Duration() (time.Duration, error)
	// Slice converts the value to []any, returning an error on failure.
	Slice() ([]any, error)
	// BoolSlice converts the value to []bool, returning an error on failure.
	BoolSlice() ([]bool, error)
	// StringSlice converts the value to []string, returning an error on failure.
	StringSlice() ([]string, error)
	// IntSlice converts the value to []int, returning an error on failure.
	IntSlice() ([]int, error)
	// Int8Slice converts the value to []int8, returning an error on failure.
	Int8Slice() ([]int8, error)
	// Int16Slice converts the value to []int16, returning an error on failure.
	Int16Slice() ([]int16, error)
	// Int32Slice converts the value to []int32, returning an error on failure.
	Int32Slice() ([]int32, error)
	// Int64Slice converts the value to []int64, returning an error on failure.
	Int64Slice() ([]int64, error)
	// UintSlice converts the value to []uint, returning an error on failure.
	UintSlice() ([]uint, error)
	// Uint8Slice converts the value to []uint8, returning an error on failure.
	Uint8Slice() ([]uint8, error)
	// Uint16Slice converts the value to []uint16, returning an error on failure.
	Uint16Slice() ([]uint16, error)
	// Uint32Slice converts the value to []uint32, returning an error on failure.
	Uint32Slice() ([]uint32, error)
	// Uint64Slice converts the value to []uint64, returning an error on failure.
	Uint64Slice() ([]uint64, error)
	// Float32Slice converts the value to []float32, returning an error on failure.
	Float32Slice() ([]float32, error)
	// Float64Slice converts the value to []float64, returning an error on failure.
	Float64Slice() ([]float64, error)
	// DurationSlice converts the value to []time.Duration, returning an error on failure.
	DurationSlice() ([]time.Duration, error)
	// StringMap converts the value to map[string]any, returning an error on failure.
	StringMap() (map[string]any, error)
	// StringMapString converts the value to map[string]string, returning an error on failure.
	StringMapString() (map[string]string, error)
	// StringMapStringSlice converts the value to map[string][]string, returning an error on failure.
	StringMapStringSlice() (map[string][]string, error)
	// StringMapBool converts the value to map[string]bool, returning an error on failure.
	StringMapBool() (map[string]bool, error)
	// StringMapInt converts the value to map[string]int, returning an error on failure.
	StringMapInt() (map[string]int, error)
	// StringMapInt64 converts the value to map[string]int64, returning an error on failure.
	StringMapInt64() (map[string]int64, error)
}

// AnyPointer holds a value and provides type conversion methods that return *T.
// On conversion failure, methods return nil.
type AnyPointer interface {
	// Bool converts the value to *bool, returning nil on error.
	Bool() *bool
	// String converts the value to *string, returning nil on error.
	String() *string
	// Int converts the value to *int, returning nil on error.
	Int() *int
	// Int8 converts the value to *int8, returning nil on error.
	Int8() *int8
	// Int16 converts the value to *int16, returning nil on error.
	Int16() *int16
	// Int32 converts the value to *int32, returning nil on error.
	Int32() *int32
	// Int64 converts the value to *int64, returning nil on error.
	Int64() *int64
	// Uint converts the value to *uint, returning nil on error.
	Uint() *uint
	// Uint8 converts the value to *uint8, returning nil on error.
	Uint8() *uint8
	// Uint16 converts the value to *uint16, returning nil on error.
	Uint16() *uint16
	// Uint32 converts the value to *uint32, returning nil on error.
	Uint32() *uint32
	// Uint64 converts the value to *uint64, returning nil on error.
	Uint64() *uint64
	// Float32 converts the value to *float32, returning nil on error.
	Float32() *float32
	// Float64 converts the value to *float64, returning nil on error.
	Float64() *float64
	// Time converts the value to *time.Time, returning nil on error.
	Time() *time.Time
	// Duration converts the value to *time.Duration, returning nil on error.
	Duration() *time.Duration
	// Slice converts the value to *[]any, returning nil on error.
	Slice() *[]any
	// BoolSlice converts the value to *[]bool, returning nil on error.
	BoolSlice() *[]bool
	// StringSlice converts the value to *[]string, returning nil on error.
	StringSlice() *[]string
	// IntSlice converts the value to *[]int, returning nil on error.
	IntSlice() *[]int
	// Int8Slice converts the value to *[]int8, returning nil on error.
	Int8Slice() *[]int8
	// Int16Slice converts the value to *[]int16, returning nil on error.
	Int16Slice() *[]int16
	// Int32Slice converts the value to *[]int32, returning nil on error.
	Int32Slice() *[]int32
	// Int64Slice converts the value to *[]int64, returning nil on error.
	Int64Slice() *[]int64
	// UintSlice converts the value to *[]uint, returning nil on error.
	UintSlice() *[]uint
	// Uint8Slice converts the value to *[]uint8, returning nil on error.
	Uint8Slice() *[]uint8
	// Uint16Slice converts the value to *[]uint16, returning nil on error.
	Uint16Slice() *[]uint16
	// Uint32Slice converts the value to *[]uint32, returning nil on error.
	Uint32Slice() *[]uint32
	// Uint64Slice converts the value to *[]uint64, returning nil on error.
	Uint64Slice() *[]uint64
	// Float32Slice converts the value to *[]float32, returning nil on error.
	Float32Slice() *[]float32
	// Float64Slice converts the value to *[]float64, returning nil on error.
	Float64Slice() *[]float64
	// DurationSlice converts the value to *[]time.Duration, returning nil on error.
	DurationSlice() *[]time.Duration
	// StringMap converts the value to *map[string]any, returning nil on error.
	StringMap() *map[string]any
	// StringMapString converts the value to *map[string]string, returning nil on error.
	StringMapString() *map[string]string
	// StringMapStringSlice converts the value to *map[string][]string, returning nil on error.
	StringMapStringSlice() *map[string][]string
	// StringMapBool converts the value to *map[string]bool, returning nil on error.
	StringMapBool() *map[string]bool
	// StringMapInt converts the value to *map[string]int, returning nil on error.
	StringMapInt() *map[string]int
	// StringMapInt64 converts the value to *map[string]int64, returning nil on error.
	StringMapInt64() *map[string]int64
}

// AnyPointerE holds a value and provides type conversion methods that return (*T, error).
// On conversion failure, methods return (nil, error).
type AnyPointerE interface {
	// Bool converts the value to *bool, returning (nil, error) on failure.
	Bool() (*bool, error)
	// String converts the value to *string, returning (nil, error) on failure.
	String() (*string, error)
	// Int converts the value to *int, returning (nil, error) on failure.
	Int() (*int, error)
	// Int8 converts the value to *int8, returning (nil, error) on failure.
	Int8() (*int8, error)
	// Int16 converts the value to *int16, returning (nil, error) on failure.
	Int16() (*int16, error)
	// Int32 converts the value to *int32, returning (nil, error) on failure.
	Int32() (*int32, error)
	// Int64 converts the value to *int64, returning (nil, error) on failure.
	Int64() (*int64, error)
	// Uint converts the value to *uint, returning (nil, error) on failure.
	Uint() (*uint, error)
	// Uint8 converts the value to *uint8, returning (nil, error) on failure.
	Uint8() (*uint8, error)
	// Uint16 converts the value to *uint16, returning (nil, error) on failure.
	Uint16() (*uint16, error)
	// Uint32 converts the value to *uint32, returning (nil, error) on failure.
	Uint32() (*uint32, error)
	// Uint64 converts the value to *uint64, returning (nil, error) on failure.
	Uint64() (*uint64, error)
	// Float32 converts the value to *float32, returning (nil, error) on failure.
	Float32() (*float32, error)
	// Float64 converts the value to *float64, returning (nil, error) on failure.
	Float64() (*float64, error)
	// Time converts the value to *time.Time, returning (nil, error) on failure.
	Time() (*time.Time, error)
	// Duration converts the value to *time.Duration, returning (nil, error) on failure.
	Duration() (*time.Duration, error)
	// Slice converts the value to *[]any, returning (nil, error) on failure.
	Slice() (*[]any, error)
	// BoolSlice converts the value to *[]bool, returning (nil, error) on failure.
	BoolSlice() (*[]bool, error)
	// StringSlice converts the value to *[]string, returning (nil, error) on failure.
	StringSlice() (*[]string, error)
	// IntSlice converts the value to *[]int, returning (nil, error) on failure.
	IntSlice() (*[]int, error)
	// Int8Slice converts the value to *[]int8, returning (nil, error) on failure.
	Int8Slice() (*[]int8, error)
	// Int16Slice converts the value to *[]int16, returning (nil, error) on failure.
	Int16Slice() (*[]int16, error)
	// Int32Slice converts the value to *[]int32, returning (nil, error) on failure.
	Int32Slice() (*[]int32, error)
	// Int64Slice converts the value to *[]int64, returning (nil, error) on failure.
	Int64Slice() (*[]int64, error)
	// UintSlice converts the value to *[]uint, returning (nil, error) on failure.
	UintSlice() (*[]uint, error)
	// Uint8Slice converts the value to *[]uint8, returning (nil, error) on failure.
	Uint8Slice() (*[]uint8, error)
	// Uint16Slice converts the value to *[]uint16, returning (nil, error) on failure.
	Uint16Slice() (*[]uint16, error)
	// Uint32Slice converts the value to *[]uint32, returning (nil, error) on failure.
	Uint32Slice() (*[]uint32, error)
	// Uint64Slice converts the value to *[]uint64, returning (nil, error) on failure.
	Uint64Slice() (*[]uint64, error)
	// Float32Slice converts the value to *[]float32, returning (nil, error) on failure.
	Float32Slice() (*[]float32, error)
	// Float64Slice converts the value to *[]float64, returning (nil, error) on failure.
	Float64Slice() (*[]float64, error)
	// DurationSlice converts the value to *[]time.Duration, returning (nil, error) on failure.
	DurationSlice() (*[]time.Duration, error)
	// StringMap converts the value to *map[string]any, returning (nil, error) on failure.
	StringMap() (*map[string]any, error)
	// StringMapString converts the value to *map[string]string, returning (nil, error) on failure.
	StringMapString() (*map[string]string, error)
	// StringMapStringSlice converts the value to *map[string][]string, returning (nil, error) on failure.
	StringMapStringSlice() (*map[string][]string, error)
	// StringMapBool converts the value to *map[string]bool, returning (nil, error) on failure.
	StringMapBool() (*map[string]bool, error)
	// StringMapInt converts the value to *map[string]int, returning (nil, error) on failure.
	StringMapInt() (*map[string]int, error)
	// StringMapInt64 converts the value to *map[string]int64, returning (nil, error) on failure.
	StringMapInt64() (*map[string]int64, error)
}

// AnyTo provides navigation to the four conversion modes.
type AnyTo interface {
	// Value returns an AnyValue for conversions that return T.
	Value() AnyValue
	// ValueE returns an AnyValueE for conversions that return (T, error).
	ValueE() AnyValueE
	// Pointer returns an AnyPointer for conversions that return *T.
	Pointer() AnyPointer
	// PointerE returns an AnyPointerE for conversions that return (*T, error).
	PointerE() AnyPointerE
}
